FROM python:3.12.4-slim

COPY requirements.txt  .
COPY main.py .
COPY models.py .
COPY utils.py .

RUN pip install --upgrade pip



RUN apt update &&\
    pip install -r requirements.txt
    

WORKDIR /app

CMD exec gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:main